# Generated by Django 4.2.7 on 2023-11-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionName', models.CharField(max_length=200, verbose_name='权限名')),
                ('permissionAPI', models.CharField(blank=True, max_length=200, verbose_name='接口')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['createTime'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=20, verbose_name='角色名')),
                ('roleNote', models.CharField(blank=True, max_length=200, verbose_name='角色说明')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rolePermission', models.ManyToManyField(to='user.permission')),
            ],
            options={
                'ordering': ['createTime'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='账号名')),
                ('realName', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('isActive', models.BooleanField(default=False, verbose_name='账号状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('userRole', models.ManyToManyField(to='user.role')),
            ],
            options={
                'ordering': ['createTime'],
            },
        ),
    ]
