# Generated by Django 4.2.7 on 2023-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rolePermission',
            field=models.ManyToManyField(blank=True, to='user.permission'),
        ),
    ]
