# Generated by Django 4.2.7 on 2023-11-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_role_rolepermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
