# Generated by Django 4.2.7 on 2023-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='账号状态'),
        ),
    ]
