# Generated by Django 4.2.7 on 2023-12-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_rolepermission_role_rolepermissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userRole',
            new_name='userRoles',
        ),
    ]
