# Generated by Django 4.2.7 on 2023-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_userrole_account_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='密码'),
        ),
    ]
